{"name": "Проверка счетчика заказов \"Выполнено за всё время\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: Element not found in ('xpath', './/input[@type=\"text\"]')\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:509:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <tests.test_feed_order.TestFeedOrders object at 0x10ca019a0>, driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"69822c66-5530-4588-b105-f5a7cb695474\")>\n\n    @allure.title('Проверка счетчика заказов \"Выполнено за всё время\"')\n    def test_counter_for_all_time(self, driver):\n        user_auth = UserAuth(driver)\n        user_auth.go_to_site(Urls.base_url)\n>       user_auth.user_auth(Account.first_user_email, Account.first_user_password)\n\ntest_feed_order.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../pages/user_auth.py:15: in user_auth\n    self.find_element_to_be_clickable(Auth.login_field)\n../pages/base_page.py:28: in find_element_to_be_clickable\n    return WebDriverWait(self.driver, time).until(EC.element_to_be_clickable(locator),\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"69822c66-5530-4588-b105-f5a7cb695474\")>, method = <function element_to_be_clickable.<locals>._predicate at 0x10ca1a550>\nmessage = 'Element not found in (\\'xpath\\', \\'.//input[@type=\"text\"]\\')'\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: Element not found in ('xpath', './/input[@type=\"text\"]')\nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:509:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n/Users/luuf/Library/Python/3.9/lib/python/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException"}, "steps": [{"name": "Авторизация пользователя", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: Element not found in ('xpath', './/input[@type=\"text\"]')\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:509:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"/Users/luuf/Library/Python/3.9/lib/python/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/luuf/Desktop/Новая папка 3/Diplom_3/pages/user_auth.py\", line 15, in user_auth\n    self.find_element_to_be_clickable(Auth.login_field)\n  File \"/Users/luuf/Desktop/Новая папка 3/Diplom_3/pages/base_page.py\", line 28, in find_element_to_be_clickable\n    return WebDriverWait(self.driver, time).until(EC.element_to_be_clickable(locator),\n  File \"/Users/luuf/Library/Python/3.9/lib/python/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "user_login", "value": "'luufqa@gmail.com'"}, {"name": "user_password", "value": "'3607833465'"}], "start": 1708856834429, "stop": 1708856845198}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1708856832390, "stop": 1708856845213, "uuid": "6c305876-561d-4553-bad0-de1a14a727f4", "historyId": "75c17094e6b840c3ee724d08bb595490", "testCaseId": "49675ea7a35899b23aa8d84db8a2f75c", "fullName": "test_feed_order.TestFeedOrders#test_counter_for_all_time", "labels": [{"name": "suite", "value": "test_feed_order"}, {"name": "subSuite", "value": "TestFeedOrders"}, {"name": "host", "value": "MacBook-Air-Aleksej.local"}, {"name": "thread", "value": "16746-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feed_order"}]}